#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication decomposePar

# runApplication $(getApplication)
runParallel $(getApplication)

#runParallel postProcess -parallel -func sample -latestTime

runApplication reconstructPar -latestTime

runApplication postProcess -func sample -latestTime

if notTest "$@"
then
    runApplication validation/plot
    # runApplication validation/plot-parallel
fi

# rmdir -r processor*

#------------------------------------------------------------------------------
