#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | www.openfoam.com
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
#    Copyright (C) 2011-2016 OpenFOAM Foundation
#    Copyright (C) 2021 OpenCFD Ltd.
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
#
# Script
#     plot
#
# Description
#     Creates .png graphs of OpenFOAM results vs experiment for the buoyant
#     cavity case
#
#------------------------------------------------------------------------------
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

# . ${WM_PROJECT_DIR:?}/etc/bashrc        # Tutorial run functions

# settings

    # stop on first error
    set -e


#------------------------------------------------------------------------------

plot_T()
{
    index="$1"
    sampleFile="$2"
    benchmarkFile="$3"

    image="OF_vs_EXPT_T$index.png"

    xMaxBenchmark="76"
    xMaxSamples="10"

    gnuplot<<PLT_T

    set tmargin 2
    set label 1 center at screen 0.8,0.8 "x/X = 0.5"
    set label 2 center at screen 0.8,0.7 "y = $index m"

    set terminal pngcairo font "helvetica,20" size 800, 500 # 1000,1000
    set grid
    # set key left top
    unset key
    # set xrange [0:0.08]
    # set xlabel "Channel width, x / [m]"
    set xrange [0:1]
    set xlabel "Non-dimensional width, z / Z"
    #set yrange [285:310]
    set ylabel "Temperature / (K)"
    set output "$image"

    # Benchmark - Experimental
        benchmark="$benchmarkFile"

    # OpenFOAM
        samples="$sampleFile"

    plot \
        samples u (\$1/$xMaxSamples):2 w lp lt -1 pt 20
PLT_T
}


plot_U()
{
    index=$1
    sampleFile="$2"
    benchmarkFile="$3"

    image="OF_vs_EXPT_U$index.png"

    xMaxBenchmark="76"
    xMaxSamples="10"

    gnuplot<<PLT_U

    set style line 1 linewidth 3 linecolor rgbcolor "#FF0000" # red
    set style line 2 linewidth 3 linecolor rgbcolor "#0000FF" # blue
    set style line 3 linewidth 3 linecolor rgbcolor "#808000" # olive
    set style line 4 linewidth 3 linecolor rgbcolor "#800080" # purple
    set style line 5 linewidth 3 linecolor rgbcolor "#008000" # green
    set style line 6 linewidth 3 linecolor rgbcolor "#00ffff" # aqua
    set style line 7 linewidth 3 linecolor rgbcolor "#000080" # navy
    set style line 8 linewidth 3 linecolor rgbcolor "#800000" # maroon

    set tmargin 2
    set label 1 center at screen 0.8,0.8 "x/X = 0.5"
    set label 2 center at screen 0.8,0.7 "y = $index m"

    set terminal pngcairo font "helvetica,20" size 800, 500 # 1000, 1000
    set grid
    set key left top
    # set xrange [0:0.08]
    # set xlabel "Channel width, x / [m]"
    set xrange [0:1]
    set xlabel "Non-dimensional width, z / Z"
    # set yrange [-0.2:0.2]
    set ylabel "Velocity Component / (m/s)"
    set output "$image"

    # Benchmark - Experimental
        benchmark="$benchmarkFile"

    # OpenFOAM
        samples="$sampleFile"

    plot \
        samples u (\$1/$xMaxSamples):3 title "Ux" w lp linestyle 1 pt 20, \
        samples u (\$1/$xMaxSamples):4 title "Uy" w lp linestyle 2 pt 20, \
        samples u (\$1/$xMaxSamples):5 title "Uz" w lp linestyle 3 pt 20
PLT_U
}


#------------------------------------------------------------------------------

# Requires "gnuplot"
command -v gnuplot >/dev/null || {
    echo "FOAM FATAL ERROR: gnuplot not found - skipping graph creation" 1>&2
    exit 1
}

SETSDIR="../postProcessing/sample"

[ -d "$SETSDIR" ] || {
    echo "FOAM FATAL ERROR: result sets not available in directory $SETSDIR" 1>&2
    exit 1
}


#------------------------------------------------------------------------------

echo ""
echo "# Plot:"
echo ""

# paths to data
#LATESTTIME=$(ls $SETSDIR)
#LATESTTIME=$(foamListTimes -case ../ -latestTime)
LATESTTIME=$(foamListTimes -case ../ -latestTime -processor)
#LATESTTIME="1000"
OFDATAROOT="$SETSDIR/$LATESTTIME"

EXPTDATAROOT=./exptData

# generate temperature profiles
TSets="0 1 2 3 4 5"
for i in $TSets
do

    echo "    processing temperature profile at y = $i"

    # OF="$OFDATAROOT/y0.${i}_T.xy"
    OF="$OFDATAROOT/y${i}_T_U.xy"

    EXPT="$EXPTDATAROOT/mt_z0_${i}0_lo.dat"

    plot_T "$i" "$OF" "$EXPT"

done

# generate velocity profiles
USets="0 1 2 3 4 5"
for i in $USets
do

    echo "    processing velocity profile at y = $i"

    # OF="$OFDATAROOT/y0.${i}_U.xy"
    OF="$OFDATAROOT/y${i}_T_U.xy"

    EXPT="$EXPTDATAROOT/mv_z0_${i}0_lo.dat"

    plot_U "$i" "$OF" "$EXPT"

done

# added
# create unified image
montage \
    OF_vs_EXPT_T5.png OF_vs_EXPT_U5.png  \
    OF_vs_EXPT_T4.png OF_vs_EXPT_U4.png  \
    OF_vs_EXPT_T3.png OF_vs_EXPT_U3.png  \
    OF_vs_EXPT_T2.png OF_vs_EXPT_U2.png  \
    OF_vs_EXPT_T1.png OF_vs_EXPT_U1.png  \
    OF_vs_EXPT_T0.png OF_vs_EXPT_U0.png  \
    -tile 2x6 -geometry 400x250          \
    mergedImg.png


image="TemperatureComparison.png"
gnuplot<<PLT_T_COMP

    set style line 1 linewidth 3 linecolor rgbcolor "#FF0000" # red
    set style line 2 linewidth 3 linecolor rgbcolor "#0000FF" # blue
    set style line 3 linewidth 3 linecolor rgbcolor "#808000" # olive
    set style line 4 linewidth 3 linecolor rgbcolor "#800080" # purple
    set style line 5 linewidth 3 linecolor rgbcolor "#008000" # green
    set style line 6 linewidth 3 linecolor rgbcolor "#00ffff" # aqua
    set style line 7 linewidth 3 linecolor rgbcolor "#000080" # navy
    set style line 8 linewidth 3 linecolor rgbcolor "#800000" # maroon

    set terminal pngcairo font "helvetica,20" size 800, 500 # 1000, 1000

    set tmargin 2
    set label 1 center at screen 0.8,0.8 "x/X = 0.5"

    set grid
    set key left top
    # set xrange [0:0.08]
    # set xlabel "Channel width, x / [m]"
    set xrange [0:1]
    set xlabel "Non-dimensional width, z / Z"
    # set yrange [-0.2:0.2]
    set ylabel "Temperature, T / (°C)"
    set output "$image"

    OF1="$OFDATAROOT/y1_T_U.xy"
    OF2="$OFDATAROOT/y2_T_U.xy"
    OF3="$OFDATAROOT/y3_T_U.xy"
    OF4="$OFDATAROOT/y4_T_U.xy"

    plot \
        OF1 u (\$1/$xMaxSamples):(\$2-273.15) title "y = 1 m" w lp linestyle 1 pt 20, \
        OF2 u (\$1/$xMaxSamples):(\$2-273.15) title "y = 2 m" w lp linestyle 2 pt 20, \
        OF3 u (\$1/$xMaxSamples):(\$2-273.15) title "y = 3 m" w lp linestyle 3 pt 20, \
        OF4 u (\$1/$xMaxSamples):(\$2-273.15) title "y = 4 m" w lp linestyle 4 pt 20
PLT_T_COMP


echo "End"


#------------------------------------------------------------------------------
